In [1]:
# Load libraries
import pandas as pd
from pandas_profiling import ProfileReport
# import numpy as np
# import matplotlib.pyplot as plt
# import seaborn as sns
# import missingno as msno

/Users/federico.gutierrez/.pyenv/versions/3.10.7/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [7]:
# Loading the dataset into a dataframe
df = pd.read_csv("df.csv", low_memory=False)

In [4]:
# df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 35 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    215 non-null    object
 1   country_code    215 non-null    object
 2   Region          215 non-null    object
 3   Indicator Name  215 non-null    object
 4   1990            185 non-null    float64
 5   1991            186 non-null    float64
 6   1992            189 non-null    float64
 7   1993            189 non-null    float64
 8   1994            189 non-null    float64
 9   1995            190 non-null    float64
 10  1996            190 non-null    float64
 11  1997            190 non-null    float64
 12  1998            189 non-null    float64
 13  1999            189 non-null    float64
 14  2000            190 non-null    float64
 15  2001            190 non-null    float64
 16  2002            191 non-null    float64
 17  2003            191 non-null    float64
 18  2004            191 non-null    float64
 19  2005            191 non-null    float64
 20  2006            191 non-null    float64
 21  2007            191 non-null    float64
 22  2008            191 non-null    float64
 23  2009            191 non-null    float64
 24  2010            191 non-null    float64
 25  2011            191 non-null    float64
 26  2012            191 non-null    float64
 27  2013            191 non-null    float64
 28  2014            191 non-null    float64
 29  2015            191 non-null    float64
 30  2016            191 non-null    float64
 31  2017            191 non-null    float64
 32  2018            191 non-null    float64
 33  2019            191 non-null    float64
 34  2019.1          191 non-null    float64
dtypes: float64(31), object(4)
memory usage: 58.9+ KB

In [8]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
1990,185.0,4.404504,5.577460,0.001183,0.434249,1.914543,6.910335,30.195189
1991,186.0,4.290648,5.577411,0.001158,0.452759,1.941825,6.497471,31.778496
1992,189.0,4.174834,5.362451,0.001130,0.471380,2.012212,6.482311,29.632441
1993,189.0,4.085472,5.385712,0.001100,0.448535,1.867589,6.430944,33.122025
1994,189.0,4.045067,5.464233,0.001071,0.406659,1.830972,6.337175,36.466263
1995,190.0,4.136628,5.510400,0.001043,0.423225,1.832534,6.360589,37.102174
1996,190.0,4.211147,5.656146,0.000000,0.461902,1.875031,6.581746,40.074177
1997,190.0,4.250716,5.857395,0.000991,0.475029,2.034502,6.478028,47.429575
1998,189.0,4.282809,5.846361,0.035567,0.496752,2.156377,6.369907,48.045021
1999,189.0,4.265652,5.917358,0.036699,0.509021,2.132253,6.233211,50.833850
2000,190.0,4.244367,5.833872,0.034603,0.514260,2.168047,6.074906,48.374002
2001,190.0,4.323111,5.855111,0.030649,0.554977,2.204862,6.227761,46.584381
2002,191.0,4.349692,6.026834,0.031324,0.574936,2.291476,6.392912,50.712155
2003,191.0,4.466854,6.132296,0.023158,0.571868,2.174082,6.818682,50.954034
2004,191.0,4.505477,6.077808,0.021033,0.585915,2.268627,6.578483,49.208051
2005,191.0,4.525854,5.954655,0.020367,0.637856,2.337149,6.514677,44.533806
2006,191.0,4.590208,5.950467,0.023660,0.625068,2.403914,6.557182,42.798308
2007,191.0,4.558706,5.778977,0.022894,0.620775,2.497948,6.699460,40.896524
2008,191.0,4.532540,5.645924,0.022151,0.589262,2.424522,6.577745,36.918708
2009,191.0,4.636380,5.528539,0.021435,0.602606,2.575052,6.888166,32.671800
2010,191.0,4.399453,5.327241,0.034580,0.614662,2.522860,6.159963,32.634302
2011,191.0,4.392175,5.284152,0.040186,0.630991,2.492730,6.269888,33.494413
2012,191.0,4.440399,5.277192,0.040017,0.633505,2.562000,6.336345,34.188222
2013,191.0,4.326678,5.203024,0.026979,0.675626,2.542694,6.069882,32.598940
2014,191.0,4.226973,5.079421,0.029121,0.669278,2.620389,5.814026,33.205895
2015,191.0,4.184129,4.985068,0.039370,0.667341,2.579300,5.776685,33.043510
2016,191.0,4.195432,4.938351,0.030715,0.728493,2.597787,5.802129,32.745888
2017,191.0,4.199802,4.869959,0.035013,0.791952,2.609976,5.834060,32.127990
2018,191.0,4.164970,4.748086,0.037113,0.795606,2.584477,5.770189,31.067533
2019,191.0,4.115138,4.714595,0.036986,0.801764,2.717624,5.585162,32.474469
2019.1,191.0,4.115138,4.714595,0.036986,0.801764,2.717624,5.585162,32.474469

In [9]:
df.head()

,Country Name,country_code,Region,Indicator Name,1990,1991,1992,1993,1994,1995,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2019.1
0,Aruba,ABW,Latin America & Caribbean,CO2 emissions (metric tons per capita),NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,South Asia,CO2 emissions (metric tons per capita),0.191745,0.167682,0.095958,0.084721,0.075546,0.068468,...,0.296506,0.259295,0.185624,0.146236,0.172897,0.149789,0.131695,0.163295,0.159824,0.159824
2,Angola,AGO,Sub-Saharan Africa,CO2 emissions (metric tons per capita),0.553662,0.544539,0.543557,0.708984,0.836804,0.912141,...,0.985522,0.950696,1.036294,1.099779,1.135044,1.031811,0.813301,0.777675,0.792137,0.792137
3,Albania,ALB,Europe & Central Asia,CO2 emissions (metric tons per capita),1.819542,1.242810,0.683700,0.638307,0.645355,0.605436,...,1.669423,1.503240,1.533630,1.668337,1.603775,1.557664,1.788786,1.782739,1.692248,1.692248
4,Andorra,AND,Europe & Central Asia,CO2 emissions (metric tons per capita),7.521832,7.235379,6.963079,6.724178,6.541579,6.733479,...,5.850886,5.944654,5.942800,5.807128,6.026182,6.080600,6.104134,6.362975,6.481217,6.481217

In [11]:
report = ProfileReport(df)

In [17]:
report.to_notebook_iframe()

ModuleNotFoundError: No module named 'ipywidgets'